apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-client.fullname" . }}
  labels:
    {{- include "odoo-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "odoo-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "odoo-client.selectorLabels" . | nindent 8 }}
    spec:
      # Image pull secrets (optionnel si image publique)
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      # Init container pour attendre PostgreSQL
      initContainers:
      - name: wait-for-db
        image: postgres:15-alpine
        command:
          - sh
          - -c
          - |
            echo "🔍 Waiting for PostgreSQL to be ready..."
            until pg_isready \
              -h {{ include "odoo-client.fullname" . }}-postgresql-0 \
              -U {{ .Values.postgresql.auth.username }} \
              -d {{ .Values.postgresql.auth.database }}; do
              echo "⏳ PostgreSQL is unavailable - sleeping..."
              sleep 5
            done
            echo "✅ PostgreSQL is ready!"
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "odoo-client.fullname" . }}-postgresql
              key: password
      
      containers:
      - name: odoo
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8069
          protocol: TCP
        - name: longpolling
          containerPort: 8072
          protocol: TCP
          
        # Variables d'environnement standard Odoo
        env:
        # Base de données PostgreSQL
        - name: DB_HOST
          value: {{ include "odoo-client.fullname" . }}-postgresql-0
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: {{ .Values.postgresql.auth.username | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "odoo-client.fullname" . }}-postgresql
              key: password
        
        # Configuration Odoo
        {{- if .Values.odoo.adminPassword }}
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "odoo-client.fullname" . }}-config
              key: admin-password
        {{- end }}
        
        # Addons personnalisés
        {{- if .Values.odoo.addonsPath }}
        - name: ADDONS_PATH
          value: {{ .Values.odoo.addonsPath | quote }}
        {{- end }}
        
        # Configuration serveur
        - name: PROXY_MODE
          value: {{ .Values.odoo.proxyMode | default "True" | quote }}
        - name: LIST_DB
          value: {{ .Values.odoo.listDb | default "False" | quote }}
        - name: DB_FILTER
          value: {{ .Values.odoo.dbFilter | default "^%d$" | quote }}
        - name: WORKERS
          value: {{ .Values.odoo.workers | default "0" | quote }}
        - name: MAX_CRON_THREADS
          value: {{ .Values.odoo.maxCronThreads | default "1" | quote }}
        
        # Variables supplémentaires
        {{- range $key, $value := .Values.odoo.extraEnv }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
          
        # Montage des volumes
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
        {{- if .Values.odoo.config }}
        - name: odoo-config
          mountPath: /etc/odoo/odoo.conf
          subPath: odoo.conf
        {{- end }}
        {{- if .Values.odoo.addons.enabled }}
        - name: odoo-addons
          mountPath: /mnt/extra-addons
        {{- end }}
          
        # Probes de santé pour Odoo officiel
        livenessProbe:
          httpGet:
            path: /web/health
            port: http
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 3
          successThreshold: 1
          
        readinessProbe:
          httpGet:
            path: /web/database/selector
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          
        startupProbe:
          httpGet:
            path: /web/database/selector
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 60  # 10 minutes max pour démarrer
          successThreshold: 1
          
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
          
        # Contexte de sécurité pour Odoo
        securityContext:
          runAsUser: 101
          runAsGroup: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          
      volumes:
      # Volume pour données Odoo
      - name: odoo-data
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "odoo-client.fullname" . }}-data
        {{- else }}
        emptyDir: {}
        {{- end }}
        
      # Volume pour configuration (optionnel)
      {{- if .Values.odoo.config }}
      - name: odoo-config
        configMap:
          name: {{ include "odoo-client.fullname" . }}-config
      {{- end }}
      
      # Volume pour addons personnalisés (optionnel)
      {{- if .Values.odoo.addons.enabled }}
      - name: odoo-addons
        {{- if .Values.odoo.addons.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "odoo-client.fullname" . }}-addons
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- end }}
        
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      terminationGracePeriodSeconds: 60
