# Configuration client
client:
  name: "argo2"
  domain: "argo2.mokatourisme.dev"

# Image Odoo officielle 18.0
image:
  repository: "odoo"
  tag: "18.0"
  pullPolicy: IfNotPresent

# Configuration Odoo
odoo:
  adminUser: "admin"
  adminPassword: "admin"
  delUser: "odoo"
  dbPassword: "odoo456"

# PostgreSQL Bitnami
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres456"
    username: "odoo"
    password: "odoo456"
    database: "argo2_odoo"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "local-path"

# Ingress - Structure simplifiée
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
  tls:
    enabled: true
    secretName: "argo2-tls"

# Ressources
resources:
  requests:
    cpu: 300m
    memory: 768Mi
  limits:
    cpu: 1000m
    memory: 2Gi

# Persistance
persistence:
  enabled: true
  size: 8Gi
  storageClass: "local-path"
