# Configuration client
client:
  name: "argo1"
  domain: "argo1.mokatourisme.dev"

# Image Odoo officielle 18.0
image:
  repository: "odoo"
  tag: "18.0"
  pullPolicy: IfNotPresent

# Configuration Odoo
odoo:
  adminUser: "admin"
  adminPassword: "admin"
  dbUser: "odoo"
  dbPassword: "odoo123"

# PostgreSQL Bitnami
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres123"
    username: "odoo"
    password: "odoo123"
    database: "argo1_odoo"
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: "local-path"

# Ingress - Structure simplifiée
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  tls:
    enabled: true
    secretName: "argo1-tls"

# Ressources
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1500m
    memory: 3Gi

# Persistance
persistence:
  enabled: true
  size: 10Gi
  storageClass: "local-path"
